StartupEvents.registry('item', e => {
  e.create('vacuum_tube_components')
  e.create('lead_anode')
  e.create('lead_cathode')
  e.create('latex_dust')
  e.create('cellulose_acetate_mesh')
  e.create('high_purity_carbon_dust')
  e.create('sugar_cane_dust')
  e.create('raw_electrode')
  e.create('graphite_electrode')
  e.create('hot_cement_clinker')
  e.create('pitch_binder')
  e.create('mineral_wool')
})