GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
    event.create('limestone', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:limstone').defaultBlockState())
        .baseModelLocation('unearthed:block/limstone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('gabbro', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:gabbro').defaultBlockState())
        .baseModelLocation('unearthed:block/gabbro')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('gabbro_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:gabbro_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/gabbro_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('phyllite', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:phyllite').defaultBlockState())
        .baseModelLocation('unearthed:block/phyllite')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('phyllite_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:phyllite_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/phyllite_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('slate', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:slate').defaultBlockState())
        .baseModelLocation('unearthed:block/slate')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('slate_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:slate_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/slate_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('granodiorite', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:granodiorite').defaultBlockState())
        .baseModelLocation('unearthed:block/granodiorite')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('granodiorite_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:granodiorite_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/granodiorite_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('rhyolite', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:rhyolite').defaultBlockState())
        .baseModelLocation('unearthed:block/rhyolite')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('rhyolite_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:rhyolite_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/rhyolite_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('white_granite', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:white_granite').defaultBlockState())
        .baseModelLocation('unearthed:block/white_granite')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('white_granite_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:white_granite_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/white_granite_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('beige_limestone', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:beige_limestone').defaultBlockState())
        .baseModelLocation('unearthed:block/beige_limestone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('beige_limestone_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:beige_limestone_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/beige_limestone_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('grey_limestone', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:grey_limestone').defaultBlockState())
        .baseModelLocation('unearthed:block/grey_limestone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('grey_limestone_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:grey_limestone_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/grey_limestone_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('siltstone', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:siltstone').defaultBlockState())
        .baseModelLocation('unearthed:block/siltstone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('siltstone_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:siltstone_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/siltstone_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('mudstone', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:mudstone').defaultBlockState())
        .baseModelLocation('unearthed:block/mudstone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('mudstone_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:mudstone_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/mudstone_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('conglomerate', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:conglomerate').defaultBlockState())
        .baseModelLocation('unearthed:block/conglomerate')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('conglomerate_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:conglomerate_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/conglomerate_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('stone_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:stone_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/stone_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('sandstone_regolith', 'ore')
        .stateSupplier(() => Block.getBlock('unearthed:sandstone_regolith').defaultBlockState())
        .baseModelLocation('unearthed:block/sandstone_regolith')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

})